part of 'theme.dart';

class AppIcons {
  AppIcons._internal();

  static final AppIcons _instance = AppIcons._internal();

  factory AppIcons() {
    return _instance;
  }

  
  IconData get maps => Icons.pin_drop_outlined;
  IconData get pinDrop => Icons.pin_drop;
  IconData get pinDrop2 => Icons.location_pin;
  IconData get saved => Icons.favorite_outline;
  IconData get jobs => Icons.work_outline;
  IconData get savedFilled => Icons.favorite;
  IconData get more => Icons.apps_outlined;
  IconData get like => Icons.thumb_up_outlined;
  IconData get likeFilled => Icons.thumb_up;
  IconData get starFilled => Icons.star_outlined;
  IconData get search => Icons.search_outlined;
  IconData get comment => Icons.comment_outlined;
  IconData get addProperty => Icons.add_home_outlined;
  IconData get locationRadius => Icons.radar_outlined;
  IconData get mapType => Icons.map_outlined;
  IconData get myLocation => Icons.my_location_outlined;
  IconData get navigation => Icons.navigation_outlined;
  IconData get share => Icons.ios_share_outlined;
  IconData get share2 => Icons.shortcut_outlined;
  IconData get rightArrow => Icons.arrow_forward_ios_outlined;
  IconData get downArrow => Icons.keyboard_arrow_down_outlined;
  IconData get moveUp => Icons.move_up_outlined;
  IconData get profile => Icons.person_outline;
  IconData get edit => Icons.edit_note_outlined;
  IconData get contactUs => Icons.support_agent_outlined;
  IconData get preference => Icons.settings_applications_outlined;
  IconData get delete => Icons.delete_outlined;
  IconData get darkMode => Icons.dark_mode_outlined;
  IconData get changeLanguage => Icons.translate_outlined;
  IconData get termsConditions => Icons.menu_book_outlined;
  IconData get speed => Icons.speed_outlined;
  IconData get cloud => Icons.cloud_outlined;
  IconData get privacyPolicy => Icons.privacy_tip_outlined;
  IconData get lock => Icons.lock_sharp;
  IconData get lock2 => Icons.lock_outline_sharp;
  IconData get back => Icons.arrow_back_ios_new_sharp;
  IconData get forward => Icons.arrow_forward_ios_sharp;
  IconData get forward2 => Icons.arrow_forward;
  IconData get download => Icons.download;
  IconData get close => Icons.close_outlined;
  IconData get add => Icons.add;
  IconData get remove => Icons.remove;
  IconData get saveProject => Icons.bookmark_border;
  IconData get colorize => Icons.colorize_outlined;
  IconData get cross => Icons.close;
  IconData get menu => Icons.menu;
  IconData get measureDistanceArea => Icons.compare_arrows;
  IconData get projects => Icons.home_work_outlined;
  IconData get drawArea => Icons.share_outlined;
  IconData get moreHorizontal => Icons.more_horiz_outlined;
  IconData get dropDownArrow => Icons.arrow_drop_down_outlined;
  IconData get dropDownArrowUp => Icons.arrow_drop_up_outlined;
  IconData get arrowdown => Icons.keyboard_arrow_down_rounded;
  IconData get myPlace => Icons.crop_free;
  IconData get social => Icons.rss_feed_outlined;
  IconData get undo => Icons.undo_outlined;
  IconData get public => Icons.public_outlined;
  IconData get joystick => Icons.control_camera_outlined;
  IconData get addChat => Icons.maps_ugc_outlined;
  IconData get emoji => Icons.emoji_emotions_outlined;
  IconData get mic => Icons.mic;
  IconData get camera => Icons.camera_alt_outlined;
  IconData get check => Icons.check;
  IconData get email => Icons.email_outlined;
  IconData get visible => Icons.visibility_outlined;
  IconData get visibleOff => Icons.visibility_off_outlined;
  IconData get calendar => Icons.date_range_outlined;
  IconData get circle => Icons.circle;
  IconData get faqs => Icons.help_outline;
  IconData get phone => Icons.phone_outlined;
  IconData get clock => Icons.access_time_outlined;
  IconData get import => Icons.upload_file_outlined;
  IconData get upload => Icons.upload_outlined;
  IconData get error => Icons.error;
  IconData get imageError => Icons.image_not_supported_outlined;
  IconData get videoError => Icons.play_disabled_outlined;
  IconData get dataSheet => Icons.storage;
  IconData get gpsIcon => Icons.radar;
  IconData get save => Icons.save_outlined;
  IconData get photoLibrary => Icons.photo_library_outlined;
  IconData get addGroup => Icons.group_add_outlined;
  IconData get notification => Icons.notifications_outlined;
  IconData get photo => Icons.photo_outlined;
  IconData get addPhoto => Icons.add_a_photo_outlined;
  IconData get pause => Icons.pause;
  IconData get play => Icons.play_arrow;
  IconData get playCircle => Icons.play_circle_outline;
  IconData get volumeOff => Icons.volume_off;
  IconData get volumeUp => Icons.volume_up;
  IconData get login => Icons.login;
  IconData get logout => Icons.logout_outlined;
  IconData get send => Icons.send;
  IconData get notificationOff => Icons.notifications_off;
  IconData get polyline => Icons.polyline_outlined;
  IconData get polygon => Icons.hexagon_outlined;
  IconData get stop => Icons.stop;
  IconData get pauseVoiceNote => Icons.pause_circle_filled;
  IconData get playVoiceNote => Icons.play_circle_fill;
  IconData get refresh => Icons.refresh_outlined;
  IconData get incommingRequest => Icons.turn_left_outlined;
  IconData get outgoingRequest => Icons.turn_right_outlined;
  IconData get color => Icons.color_lens_outlined;
  IconData get payment => Icons.payment_outlined;
  IconData get profileCircle => Icons.account_circle_rounded;
  IconData get chatOutlined => Icons.chat_outlined;
  IconData get chatRounded => Icons.chat_rounded;
  IconData get filter => Icons.filter_alt_outlined;
  IconData get ads => Icons.feed_outlined;
  IconData get attachment => Icons.attach_file_outlined;
  IconData get adsClick => Icons.ads_click;
  IconData get role => Icons.people_outline_outlined;
  IconData get arrowOutward => Icons.arrow_outward_rounded;
  IconData get copy => Icons.copy_outlined;

}
